### ISSUE TITLE
vineyardd missing from pip packages

### ISSUE THREAD

**Issue by leezu** [alibaba/libvineyard#165]
Hi, I'm trying out vineyard as alternative to PyArrow Plasma, given that the latter is currently unmaintained.

https://v6d.io/notes/getting-started.html#starting-vineyard-server recommends running vineyardd, whereas https://v6d.io/notes/install.html#install-vineyard recommends installing vineyard from pypi.

Unfortunately https://pypi.org/project/vineyard/ does not contain the vineyardd binary. Is it intended?

**Comment by sighingnow** [comment]
The prebuilt `vineyardd` binary is available at https://github.com/alibaba/libvineyard/releases, but we haven't distributed prebuilt `vineyardd` binary for Mac yet.

But that is already in our todolist, the `vineyardd` will be included in the next release, before the end of this week.

**Comment by sighingnow** [comment]
We have just released v0.1.9 and have vineyardd bundled in the wheel packages: https://pypi.org/project/vineyard/0.1.9/.

Closed as fixed by #188.
