### ISSUE TITLE
cmake: required dependency on grapelite

### ISSUE THREAD

**Issue by leezu** [alibaba/libvineyard#166]
https://github.com/alibaba/libvineyard/blob/053fb4119ac00490d7bf0ce7d2ec1c5c9a7ddd7e/modules/basic/CMakeLists.txt#L5

grapelite is listed as required dependency, even when building with `-DBUILD_VINEYARD_GRAPH=0`

**Comment by sighingnow** [comment]
`OutArchive/InArchive` types from libgrape-lite, absolutely that should be fixed.

**Comment by sighingnow** [comment]
Hi @leezu now `vineyard_basic` no longer requires libgrapelite after #167 merged.
